### ISSUE TITLE
Critical: --features onnx fails to compile with ort 2.0.0-rc.12 API drift

### ISSUE THREAD

**Issue by SuperInstance** [SuperInstance/pincher#10]
## Critical: `--features onnx` fails to compile with ort 2.0.0-rc.12

**Severity:** Critical (feature-gated code is completely non-functional)

### Background

The previous fix (commit `9fc2e49`) adapted the `Session::builder()` chain for `ort 2.0.0-rc.12`, but additional API drift in that same release was **not** caught because CI only tests default features. Building with `--features onnx` produces 4 compilation errors.

### Errors

```
error[E0432]: unresolved import `ort::prelude`
  --> pincher-core/src/embed/onnx.rs:21:10
   |
21 | use ort::prelude::*;
   |          ^^^^^^^ could not find `prelude` in `ort`

error[E0277]: `?` operator cannot be applied to `[SessionInputValue<'_>; 3]`
   --> pincher-core/src/embed/onnx.rs:348:35

error[E0599]: no method named `shape` found for tuple `(&ort::value::Shape, &[f32])`
   --> pincher-core/src/embed/onnx.rs:358:28

error[E0277]: `(&ort::value::Shape, &[f32])` cannot be indexed by `[usize; 3]`
   --> pincher-core/src/embed/onnx.rs:373:37
```

### Root Cause

`ort 2.0.0-rc.12` made these additional breaking changes beyond the `Session::builder()` chain already fixed:

1. **`ort::prelude` removed** — was a convenience re-export module, now removed
2. **`session.run()` return type changed** — returns `Result<SessionOutput>` where `SessionOutput` indexing and method shape API differs from rc.11
3. **`Value::shape()` API changed** — returns a `(&Shape, &[f32])` tuple instead of a `Shape` ref with `.shape()` method
4. **Indexing syntax changed** — `output[[0, t, d]]` no longer works with the new output type

### Impact

- Any deployment using `--features onnx` (the primary text embedding path) **cannot compile**
- The fallback hash embedding still works (default features), but ONNX vector search quality is unavailable
- CI doesn't catch this because it only builds with default features

### Recommended Fix

1. Consult `ort 2.0.0-rc.12` changelog/docs for the final API shape
2. Update `pincher-core/src/embed/onnx.rs` to use the new `SessionOutput`, `Value::try_extract_tensor`, and proper indexing
3. Add `--features onnx` to the CI matrix

### Additional Issues Discovered During Audit

See the full audit bottle at `i2i-vessel/bottles/pincher-audit-2026-06-15.md` for additional findings including:

- `ternary-types` version conflict (v0.1.0 vs v0.2.0 in same workspace)
- `silo-core` unused workspace dependency
- `ndarray` 0.16 in hybrid-bridge vs 0.17 in pincher-core
- `thiserror` v1 nearing EOL
- No `cargo-deny` / `cargo-audit` in CI
- No aarch64 CI runner
